# Configuration for Travis-CI continuous integration.
#
# Copyright 2015-2017, 2019 Russ Allbery <eagle@eyrie.org>
#
# SPDX-License-Identifier: GPL-1.0-or-later OR Artistic-1.0-Perl

language: perl
perl:
  - "5.28"
  - "5.26"
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"

# Only run the exhaustive tests with heavy dependencies on the latest Perl
# version.  (These conditionals are written weirdly backwards so that the
# command line evaluates to true.)
#
# Don't fail the test if Test::MinimumVersion or Test::Perl::Critic cannot
# be installed, since this seems to fail very regularly on Travis-CI.

env: AUTHOR_TESTING=1
before_install:
  - test "$TRAVIS_PERL_VERSION" != "5.28" || cpanm JSON::PP
  - test "$TRAVIS_PERL_VERSION" != "5.28" || cpanm Perl6::Slurp
  - test "$TRAVIS_PERL_VERSION" != "5.28" || cpanm Perl::Critic         || true
  - test "$TRAVIS_PERL_VERSION" != "5.28" || cpanm Test::MinimumVersion || true
  - test "$TRAVIS_PERL_VERSION" != "5.28" || cpanm Test::Perl::Critic   || true
  - test "$TRAVIS_PERL_VERSION" != "5.28" || cpanm Test::Pod
  - test "$TRAVIS_PERL_VERSION" != "5.28" || cpanm Test::Strict
  - test "$TRAVIS_PERL_VERSION" != "5.28" || cpanm Test::Synopsis
